apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-staging
  labels:
    app: be-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be-staging
  template:
    metadata:
      labels:
        app: be-staging
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: be-staging
          image: devops6th-cr.kr.ncr.ntruss.com/lion-app:0.3.1
          envFrom:
            - secretRef:
                name: be-secret-staging
            - secretRef:
                name: db-secret
            - configMapRef:
                name: be-config-staging
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: be-staging
spec:
  type: LoadBalancer
  selector:
    app: be-staging
  ports:
    - port: 80
      targetPort: 8000
