apiVersion: v1
kind: Pod
metadata:
  name: db-prod
  labels:
    app: db-prod
spec:
  containers:
    - name: db-prod
      image: postgres:13
      envFrom:
        - secretRef:
            name: db-secret
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          subPath: k8s
          name: pg-data

  volumes:
    - name: pg-data
      persistentVolumeClaim:
        claimName: db-prod-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db-nodeport-prod
spec:
  type: NodePort
  selector:
    app: db-prod
  ports:
    - port: 5432
      targetPort: 5432
