apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lion.fullname" . }}
  labels:
    {{- include "lion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "lion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lion.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ include "lion.fullname" . }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ include "lion.fullname" . }}
            - secretRef:
                name: {{ include "lion.db.fullname" . }}
            - configMapRef:
                name: {{ include "lion.fullname" . }}
          ports:
            - containerPort: {{ .Values.containerPort.django }}
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5