apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap
  labels:
    app: fortune
spec:
  containers:
    - name: html-generator
      image: hjklo0220/fortune:env
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
      volumeMounts:
        - mountPath: /var/www
          name: html

    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
  volumes:
    - name: html
      emptyDir: {}
