image:
  name: devops6th-cr.kr.ncr.ntruss.com/lion-app
  tag: ""
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred
  db:
    name: postgres
    tag: 13

nameOverride: ""
fullnameOverride: ""

replicas: 3

service:
  lb:
    type: LoadBalancer
    port: 80
  db:
    type: NodePort
    port: 5432

containerPort:
  django: 8000
  db: 5432

secret:
  type: Opaque
  django:
    DJANGO_SECRET_KEY: be74bixeol1-o0@zvm_$gw!(ce28p+y=dlm=+aodr4(vk&enx2
  db:
    POSTGRES_DB: lionforum
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_PORT: "5432"

configMap:
  django:
    DJANGO_SETTINGS_MODULE: lion_app.settings.prod
