apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap
    labels:
{{ include "mychart.app" . | indent 8}}
data:
    myvalue: "Hello world!"
    {{- range $key, $val := .Values.favorites }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    toppings: |-
        {{- range $key, $value := .Values.pizzaToppings }}
        - {{ $key }}: {{ $value | title | quote}}
        {{- end }}
    sizes: |-
        {{- range tuple "small" "medium" "large" }}
        - {{ . }}
        {{- end }}
{{ include "mychart.app" . | indent 4 }}
