apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db
      image: postgres:13
      # env:
      #   - name: PGDATA
      #     value: /var/lib/postgresql/data/k8s
      envFrom:
        - secretRef:
            name: db-secret
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          subPath: k8s
          name: pg-data

  volumes:
    - name: pg-data
      persistentVolumeClaim:
        claimName: db-pod-pvc
